language: node_js
node_js: lts/*
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add surge
install:
  - yarn install
script:
  - yarn website:build
cache:
  yarn: false
after_success:
  - node scripts/deploy/pull-request.js
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: next
    local-dir: packages/react-impression-website/dist
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy/branch.js
    on:
      branch: qiniu
